### PR TITLE
add classes hook for customizations

### PR DESCRIPTION
**Pull request by atmonshi**
- the main container: `fi-preset-color-picker`
- for items: `fi-preset-color-picker-item`
- for active/selected item: `fi-preset-color-picker-item-active`

### CODE REVIEW

**Comment by atmonshi** [comment]
not sure if it should be documented but I added either way

**Comment by awcodes** [comment]
Can you change these to maybe 'pcp-' instead of 'fi-'?

I don't want people to think they are filament hooks.

😀

**Comment by atmonshi** [comment]
fair, from dev pov, my eye used to scan `fi-` for classes in the source 😅

**Comment by awcodes** [comment]
sweet, thanks.

**Pull request merged**
